### ISSUE TITLE
Gogo anime 

### ISSUE THREAD

**Issue by akumarsmapp** [Darkprnce/CAnime#1]
Gogo anime change website is https://gogoanime.cl/ connection reset is not working and this connection reset?
But gogo anime create website https://www3.gogoanimes.fi/ and this new website create gogo anime
Please request 🥺🙏 for aniyomi staff and create see this problem

**Comment by Darkprnce** [comment]
i have fixed both gogoanime and zoro, you can update the app to the latest version watch anime easily. I have fixed some other bugs as well and added notification list to view all notifications.
